modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="diamond"
version="2.4"
displayName="Diamond Mod"
authors="ZiYueCommentary"
logoFile="diamond_logo.png"
description="dIamONds!"

[[dependencies.diamond]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.diamond]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
